// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgmUv2EUWFHvutqrxOocIQrb5c7_q2XFY',
    appId: '1:1077126277768:web:657c4656a1202346f20d3d',
    messagingSenderId: '1077126277768',
    projectId: 'iti-movie-app-bacb2',
    authDomain: 'iti-movie-app-bacb2.firebaseapp.com',
    storageBucket: 'iti-movie-app-bacb2.firebasestorage.app',
    measurementId: 'G-TGLP6QEPPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-SN_GbKniSOQGPtXr9ZscbVRnXFbCbM',
    appId: '1:1077126277768:android:d68a8fe27c3b625ef20d3d',
    messagingSenderId: '1077126277768',
    projectId: 'iti-movie-app-bacb2',
    storageBucket: 'iti-movie-app-bacb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGi3Cm-fbPcvv-EBfWmC54fEsmlfw2b7g',
    appId: '1:1077126277768:ios:a1c822993629b543f20d3d',
    messagingSenderId: '1077126277768',
    projectId: 'iti-movie-app-bacb2',
    storageBucket: 'iti-movie-app-bacb2.firebasestorage.app',
    iosBundleId: 'com.example.itiMovieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgmUv2EUWFHvutqrxOocIQrb5c7_q2XFY',
    appId: '1:1077126277768:web:4f6ece3872ebb3e9f20d3d',
    messagingSenderId: '1077126277768',
    projectId: 'iti-movie-app-bacb2',
    authDomain: 'iti-movie-app-bacb2.firebaseapp.com',
    storageBucket: 'iti-movie-app-bacb2.firebasestorage.app',
    measurementId: 'G-B68NBPNGRQ',
  );
}
